version: '3'
services:
  db:
    image: 'registry.redirectme.net/postgres:9.6'
    restart: always
    environment:
    - POSTGRES_PASSWORD=builder
    - POSTGRES_USER=builder
    - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=ru_RU.utf8 --lc-collate=ru_RU.utf8 --lc-ctype=ru_RU.utf8
    volumes:
    - ../dump:/var/dump
    ports:
    - "5432:5432"
  pgadmin:
    image: 'fenglc/pgadmin4'
    ports:
    - "5051:5050"
    environment:
    - DEFAULT_USER=q@q
    - DEFAULT_PASSWORD=qwerty
    depends_on:
    - db
